# Site settings
title: Sebastian Ploch
email: sebastianploch@protonmail.com
url: https://sebastianploch.me
description: "This is portfolio website for anything that has to do with
  Sebastian Ploch, be it personal,academic or professional.
  Content is focused around programming and game development predominantly."
keywords: "programmer, games, graphics, gameplay, c++"
skills: "Games Programmer"
meta_author: Ploch Sebastian

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 212d40 #80B3FF
  primary-rgb: "33,45,64" #"128,179,255"
  secondary: 364156 #FD6E8A
  secondary-dark: 11151c #A2122F

# Footer settings
footer:
  copyright: Sebastian Ploch
  social: Find me at 

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/sebastianploch
  - title: linkedin
    url: https://www.linkedin.com/in/sebastian-ploch
  - title: github
    url: https://github.com/limanniel

# Credits content
# credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
