# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Sebastian Ploch
subtitle: My coding den!
description: >- # this means to ignore newlines until "baseurl:"
  This is portfolio website for anything that has to do with
  Sebastian Ploch, be it personal,academic or professional.
  Content is focused around programming and game development predominantly.
author: Sebastian Ploch
email: sebastianploch@pm.me
avatar: assets/images/avatar.jpg

# You'll want to customize url and baseurl for your own site:
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sebastianploch.me" # the base hostname & protocol for your site 

# Plugins
plugins:
  - jekyll-feed
  - jemoji

# Social settings
# Make sure to include the full url including protocol, e.g. https://github.com/chrisbobbe
twitter_url:
instagram_url: 
linkedin_url: https://www.linkedin.com/in/sebastian-p-b15b3a171
github_url: https://github.com/limanniel
pinterest_url:
slack_url:

# Google Analytics Tracking ID goes here:
google_analytics: UA-141490401-1

# The following settings are NECESSARY for the Prologue theme to run:
remote_theme: chrisbobbe/jekyll-theme-prologue
collections: [sections]
